/* eslint-disable import/prefer-default-export */
export const ARTICLE_DATA = [
  {
    title: 'string',
    description: 'string',
    body: 'strinfghjhhg',
    createdAt: '2019-06-19T09:16:23.749462Z',
    updatedAt: '2019-06-19T09:16:23.749489Z',
    author: {
      email: 'cedric.lusiba@andela.com',
      username: 'cdv1x',
      bio: '',
      image: '',
      gender: '',
      first_name: '',
      last_name: '',
      location: '',
      birth_date: null,
    },
    slug: 'string',
    image: 'http://string.com',
    average_rating: 0,
    tagName: [],
  },
  {
    title: 'it tgf friday',
    description: 'day of the week',
    body: "You can't miss this tdf friday in ruby",
    createdAt: '2019-06-20T13:17:46.909484Z',
    updatedAt: '2019-06-20T13:17:46.909533Z',
    author: {
      email: 'alexxsanya@gmail.com',
      username: 'alexxsanya',
      bio: '',
      image: '',
      gender: 'male',
      first_name: 'Alex',
      last_name: 'Sanya',
      location: '',
      birth_date: null,
    },
    slug: 'friday',
    image: 'https://via.placeholder.com/236x124',
    average_rating: 0,
    tagName: [],
  }];
