export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const PROFILE_LOADING = 'IS_LOADING';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'DIT_PROFILE_FAILURE';
export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
